### ISSUE TITLE
ISO installation is catastrophically broken (install script was too, but is now fixed)

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1382]
Tried to launch it and it failed with this error:

```
Paramétrage de libnet-smtp-ssl-perl (1.04-1) ...
Paramétrage de libhtml-format-perl (2.12-1) ...
Paramétrage de php-php-gettext (1.0.12-0.1) ...
Paramétrage de python3-numpy (1:1.12.1-3) ...
Paramétrage de libtk8.6:amd64 (8.6.6-1+b1) ...
Paramétrage de tk8.6-blt2.5 (2.5.3+dfsg-3) ...
Paramétrage de python3-matplotlib (2.0.0+dfsg1-2) ...
Paramétrage de php-gettext (1.0.12-0.1) ...
Paramétrage de blt (2.5.3+dfsg-3) ...
Paramétrage de libmailtools-perl (2.18-1) ...
Paramétrage de python3-tk:amd64 (3.5.3-1) ...
Paramétrage de libwww-perl (6.15-1) ...
Paramétrage de liblwp-protocol-https-perl (6.06-2) ...
Traitement des actions différées (« triggers ») pour libc-bin (2.24-11+deb9u4) ...
Traitement des actions différées (« triggers ») pour systemd (232-25+deb9u11) ...
Traitement des actions différées (« triggers ») pour php7.0-fpm (7.0.33-0+deb9u3) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Impossible de configurer « debhelper:amd64 ».
E: Impossible d'effectuer la configuration immédiate de « dh-autoreconf:amd64 ». Veuillez consulter la page de manuel apt.conf(5) et notamment la section à propos de APT::Immediate-Configure, pour plus d'informations. (2)
[ESC[1mESC[31mFAILESC[0m] Installation of Yunohost packages failed
[ESC[1mESC[34mINFOESC[0m] Installation logs are available in /var/log/yunohost-installation_20190715_003929.log
```

Here is the last 1000 lines of logs as yunopaste refuse the full log since it's too big https://paste.yunohost.org/lujovavago

**Comment by Psycojoker** [comment]
So, that looks pretty stupid, I can't reproduce easily right now but I'm expecting apt to be super annoying and not returning "0" because it has emit a warning, which is super annoying. When I rerun the command by hand I get this:

```
root@meuf:~# apt-get -o Dpkg::Options::="--force-confold" -o APT::install-recommends=true  -y --force-yes install  yun
ohost yunohost-admin postfix
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances     
Lecture des informations d'état... Fait
postfix is already the newest version (3.1.12-0+deb9u1).
yunohost is already the newest version (3.6.4.3).
yunohost-admin is already the newest version (3.6.4).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
```

**Comment by Psycojoker** [comment]
Related part of the code https://github.com/YunoHost/install_script/blob/f4839a7e712a6b67cd398f6da2494987040cfa69/install_yunohost#L476-L481

**Comment by alexAubin** [comment]
Yea I noticed that a few days ago as well as some users ... I don't know why that happens ... That sounds unrelated to YunoHost directly, and more related to apt itself not being fully happy with debhelper for some reason ? 

Yet relaunching a `dpkg --configure -a` or `apt install -f` does not trigger anything, it's happy with it, just somehow reports a message during the initial install, idk ... Still quite annoying as it sounds as something got broken or didnt work

**Comment by Psycojoker** [comment]
Yeah and the reload part of the installation isn't run which is annoying and could create some bugs. If I find time I'll try to play with digital ocean during the week to debug that somehow but can't guaranteed it :/

**Comment by decentral1se** [comment]
Ah, I think I ran into this then. I saw this:

```
...
[FAIL] Installation of Yunohost packages failed
...
```

And then:

```
root@vpsnew-decentral1-se:~# dpkg --configure -a
dpkg: dependency problems prevent configuration of debhelper:
 debhelper depends on dpkg-dev (>= 1.18.2~); however:
  Package dpkg-dev is not installed.
 debhelper depends on libdpkg-perl (>= 1.17.14); however:
  Package libdpkg-perl is not installed.
 debhelper depends on po-debconf; however:
  Package po-debconf is not installed.

dpkg: error processing package debhelper (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dh-autoreconf:
 dh-autoreconf depends on debhelper; however:
  Package debhelper is not configured yet.

dpkg: error processing package dh-autoreconf (--configure):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.60) ...
Processing triggers for php7.0-fpm (7.0.33-0+deb9u3) ...
dpkg: dependency problems prevent configuration of dh-strip-nondeterminism:
 dh-strip-nondeterminism depends on debhelper; however:
  Package debhelper is not configured yet.

dpkg: error processing package dh-strip-nondeterminism (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Processing triggers for systemd (232-25+deb9u11) ...
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for resolvconf (1.79) ...
Processing triggers for dbus (1.10.28-0+deb9u1) ...
Processing triggers for rsyslog (8.24.0-1) ...
Errors were encountered while processing:
 debhelper
 dh-autoreconf
 dh-strip-nondeterminism
```

And a `apt install -f` fixed it. Then I just ran the `curl|bash` again and it was fixed.

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/install_script/commit/465d9493aa4d690dff034f2a746178dbb8e71625 I think ...

**Comment by decentral1se** [comment]
Yes, nice one! I fired up a quick box and ran:

```
$ curl https://raw.githubusercontent.com/YunoHost/install_script/465d9493aa4d690dff034f2a746178dbb8e71625/install_yunohost | bash
```

and it worked a charm.

**Comment by alexAubin** [comment]
Still not sure what happened though ... That thing with `debhelper` seems very much unrelated to Yunohost itself :/

**Comment by Psycojoker** [comment]
Let's close that for now and re-open if needed.

Thx for the patch!

**Comment by alexAubin** [comment]
Reopening because the ISO is still very broken

c.f. [this toot](https://mastodon.social/@yunohost/102558997704167249)

**Comment by alexAubin** [comment]
This is fixed by https://github.com/YunoHost/cd_build/commit/161292c1fc1b328416d6b2ee3111c28248e03302 and the next commit ! Thanks to @zamentur !
