### ISSUE TITLE
ynh_install_app_dependencies fails silently to install all dependencies ... ? / Sury repo fucks up php7.0 deps

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1407]
Relevant log is here : https://paste.yunohost.org/raw/xomijogitu

with the main error being : 

```text
2019-08-08 10:02:10,366: DEBUG - PHP module zip not installed.
2019-08-08 10:02:10,367: WARNING - Unable to install Nextcloud
```

But that's weird because `php-zip` was explicitly asked to be installed ...

Digging with the user that encountered this issue we found that : 

```text
$ apt install php7.0-zip
The following packages have unmet dependencies: 
    php7.0-zip : Depends: php7.0-common (= 7.0.33-0+deb9u3) but 7.0.33-9+0~20190712.17+debian9~1.gbp3af52c is to be installed
```

And indeed : 

```text
$ apt-cache policy php7.0-common
Installed: 7.0.33-9+0~20190712.17+debian9~1.gbp3af52c 
Candidate: 7.0.33-9+0~20190712.17+debian9~1.gbp3af52c
Version table:
*** 7.0.33-9+0~20190712.17+debian9~1.gbp3af52c 100 
    100 /var/lib/dpkg/status
     7.0.33-0+deb9u3 500 
500 http://mirrors.digitalocean.com/debian stretch/main amd64 Packages
 500 http://security.debian.org stretch/updates/main amd64 Packages  
```

So imho there are two issues in there : 
- `ynh_install_app_dependencies` never explicitly complain (even in the debug output) about not being able to install php-zip ?
- Where does this version `7.0.33-9+0~20190712.17+debian9~1.gbp3af52c` comes from ? I believe it's related to other apps (the user was telling it also installed pixelfed) which installed some stuff from sury and for some reason end up with this package ... This is pretty annoying as it overrides the default debian package ... Dunno what we could do with this, maybe try to have a higher pin for debian (or lower pin for sury ?)

**Comment by maniackcrudelis** [comment]
> ynh_install_app_dependencies never explicitly complain (even in the debug output) about not being able to install php-zip ?

It was supposed to
https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/helpers.d/apt#L189
https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/helpers.d/apt#L232

Maybe something went wrong with the return code of apt.

Pixelfed now uses `ynh_install_php` to not have those issues. It would be interesting to know when he did install this app.
If it was recently, with this new helper, that would mean the problem isn't solved by the helper.
This app has been fixed in late April this year.

**Comment by alexAubin** [comment]
>Pixelfed now uses ynh_install_php to not have those issues. It would be interesting to know when he did install this app.
If it was recently, with this new helper, that would mean the problem isn't solved by the helper.
This app has been fixed in late April this year.

In fact I asked the user to see if there was any `sury` repo somewhere in `/etc/apt/` and there wasnt, so I think I concluded that : 
- `ynh_install_php` was indeed used I believe
- my guess is that during the install of php7.3, somehow this weird version of php7.0-common got installed ... ? Maybe we could try to reproduce the issue by installing pixelfed on some test instance and see if something happened to php7.0-common's version...

**Comment by yalh76** [comment]
Tested on a fresh Yunohost.
Before pixelfed installation: 
```
php7.0-common:
  Installed: 7.0.33-0+deb9u3
  Candidate: 7.0.33-0+deb9u3
  Version table:
 *** 7.0.33-0+deb9u3 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
        100 /var/lib/dpkg/status
```

After pixelfed installation:
```
php7.0-common:
  Installed: 7.0.33-10+0~20190807.18+debian9~1.gbp5452d8
  Candidate: 7.0.33-10+0~20190807.18+debian9~1.gbp5452d8
  Version table:
 *** 7.0.33-10+0~20190807.18+debian9~1.gbp5452d8 995
        995 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     7.0.33-0+deb9u3 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
```

**Comment by yalh76** [comment]
pixelfed use ynh_install_php since 28 march 2019 https://github.com/YunoHost-Apps/pixelfed_ynh/commit/df8658af5a54bbe1dcd0cc486e2f8f6e9f7bf23d#diff-dc2801cb46a5d60e62234cff98084498

**Comment by alexAubin** [comment]
Ah, thanks for the test ! So at least we have an easy way to reproduce the issue :P

**Comment by yalh76** [comment]
Here are the logs of the installation: https://paste.yunohost.org/raw/jegoyunate

**Comment by yalh76** [comment]
the issue comes from:
```
2019-08-09 00:40:39,615: DEBUG - The following packages will be upgraded:
2019-08-09 00:40:39,616: DEBUG -   libpcre3 php7.0-cli php7.0-common php7.0-curl php7.0-fpm php7.0-gd
2019-08-09 00:40:39,616: DEBUG -   php7.0-intl php7.0-json php7.0-ldap php7.0-mbstring php7.0-mcrypt
2019-08-09 00:40:39,616: DEBUG -   php7.0-mysql php7.0-opcache php7.0-readline php7.0-xml
```
Maybe a pinning issue ^^

**Comment by alexAubin** [comment]
Yeah it's not clear for me if it really is needed to upgrade those to install php7.3-fpm for some reason, or if it just happens to upgrade them because it can ?

I naively think it's the first option though I'm not sure ... But it doesn't look like usually installing a package with equivs would trigger an upgrade of any package that can be upgraded ... So it's probably because some packages requires php7.0-common (et al.) version to be higher than the vanilla debian version ?

**Comment by alexAubin** [comment]
(Maybe `aptitude why php7.0-common` after the pixelfed install can shed some light)

**Comment by yalh76** [comment]
First response was:
`-bash: aptitude: command not found`

After `apt install aptitude`

```
i   yunohost    Depends php-intl
i A php-intl    Depends php7.0-intl
i A php7.0-intl Depends php7.0-common (= 7.0.33-10+0~20190807.18+debian9~1.gbp5452d8)
```

**Comment by alexAubin** [comment]
Note that we investigated this - more precisely the thing about the weird php7.0 depencies - with @yalh76 during the Brique Camp 
- This is definitely an issue triggered by installing PHP 7.X from Sury
- For example, some php7.3 dependencies requires (directly or indirectly) php7.0-common to be *strictly* > 7.0.33-0 
- This means that the default debian version is not enough, and therefore php7-0-common version 7.0.33-10-blah-blah-blah is installed from Sury
- Which then triggers a cascade of upgrade for other php7.0 packages to be consistent with the new php7.0-common version
- Once the sury repo is removed and a new php7.0 dependency needs to be installed, it can't, because it needs to fetch a version consistent with other php7.0 packages already installed, but Sury ain't there anymore.


.... Now that I think about it, maybe a dirty workaround would be that, when Sury gets configured, it also installs *all usual php7.0 depencies from this repo* (even if not explicitly needed). That could prevent some issues like nextcloud requesting a not-already-installed-dep

(idk if that makes sense)

**Comment by yalh76** [comment]
> .... Now that I think about it, maybe a dirty workaround would be that, when Sury gets configured, it also installs _all usual php7.0 depencies from this repo_ (even if not explicitly needed). That could prevent some issues like nextcloud requesting a not-already-installed-dep
> 
> (idk if that makes sense)

Very dirty workaround.... Would be better to deep dive in Sury package to understand why it installs PHP-7.0.33-10+0~20190807.18 or add Sury repository definitively...

**Comment by alexAubin** [comment]
>understand why it installs PHP-7.0.33-10+0~20190807.18

We looked at this together the other day and found that some php7.3 package (I don't remember which one) requires php7.0-common strictly higher than 7.0.33-0 - the one provided by Debian - compared to 7.0.33*-10* provided by Sury :confused:

**Comment by alexAubin** [comment]
Random other idea, but there seem to be something called phpenv who might help us managing php versions in a way similar to python virtualenv or `n`/`nvm` for nodejs ...

https://github.com/phpenv/phpenv

I don't know what it's worth though ... but at least it seems to be an active project ... maybe other php experts would have some idea on this

**Comment by yalh76** [comment]
Well, deep diving in php7.3-common:
```
Package: php7.3-common
Source: php7.3
Version: 7.3.8-1+0~20190807.43+debian9~1.gbp7731bf
Architecture: amd64
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 6470
Depends: php-common (>= 1:35), ucf, libc6 (>= 2.15), libssl1.1 (>= 1.1.0)
Breaks: gforge-common (<< 6), php7.0-curl (<< 7.0.33-1~), php7.2-sodium (<< 7.2.12~)
```
And current php7.0-curl version is 7.0.33-0+deb9u3 for stretch, it's why php7.0 is updated in the process of installing php7.3.

**Comment by gnouts** [comment]
Hello, what can be done to workaround this ? 

I had a bad upgrade which removed my nextcloud app.

Now I can't restore the backup because "Unable to install dependencies" for nextcloud-ynh-deps.
(https://paste.yunohost.org/raw/ozobozoboq)

I really need nextcloud for my daily work, what can I do ? Can some of you help me modifying the backup to skip this part, or install manually something ? I'm afraid to break even more app that use php...

**Comment by alexAubin** [comment]
A workaround I believe is to re-add the sury repository, so something like : 

```
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/sury.list
wget -O /etc/apt/trusted.gpg.d/sury.gpg https://packages.sury.org/php/apt.gpg
```

Then you can validate that adding the repo worked using 

```
apt update
```

@maniackcrudelis @yalh76 : Dunno if you have some idea of a quick fix that could easily be implemented and deployed but that's really an important issue right now ...

**Comment by gnouts** [comment]
Ok... After first panic is passed, I read this thread one more time. And understand I had the sury repo missing.

I added the sury repo again in apt source.list and the restore worked just fine.

Edit : thanks @alexAubin,  this is exactly what I did, thanks for quick reply :)

**Comment by decentral1se** [comment]
FTR, we've had a discussion about this and there are some notes (line 30):

> https://pad.lqdn.fr/p/yunohost-17-09-2019

**Comment by alexAubin** [comment]
Yet another case of this kind of issue ... https://forum.yunohost.org/t/pb-lors-de-linstallation-de-wallabag/9083 ... This is really one of the biggest issue in Yunohost right now ...

**Comment by alexAubin** [comment]
Fucking fix released in 3.6.5
